@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "telemetry.Main#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 7,
    "backwardDepth": 7,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 8,
    "showCallOrder": true,
    "edgeMode": "TypesAndMethods", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": true
  },
  "rootClass": "telemetry.Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_780346297 { 
   	label=telemetry
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1666710254 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main780346297XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_587464905 { 
   	label=Config
	labeljust=l
	fillcolor=white
	style=filled
   
   Config780346297XXXgetDimFile0[
	label="+ getDimFile()"
	style=filled
	fillcolor=white
	tooltip="Config

null"
	fontcolor=darkgreen
];

Config780346297XXXgetTmFile0[
	label="+ getTmFile()"
	style=filled
	fillcolor=white
	tooltip="Config

null"
	fontcolor=darkgreen
];

Config780346297XXXgetXmlFile0[
	label="+ getXmlFile()"
	style=filled
	fillcolor=white
	tooltip="Config

null"
	fontcolor=darkgreen
];

Config780346297XXXload1808118735[
	label="+ load()"
	style=filled
	fillcolor=white
	tooltip="Config

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_937179636 { 
   	label=TelemetryDialog
	labeljust=l
	fillcolor=white
	style=filled
   
   TelemetryDialog780346297XXXTelemetryDialog0[
	label="+ TelemetryDialog()"
	style=filled
	fillcolor=white
	tooltip="TelemetryDialog

null"
	fontcolor=darkgreen
];

TelemetryDialog780346297XXXsetDefaultFiles924985979[
	label="+ setDefaultFiles()"
	style=filled
	fillcolor=white
	tooltip="TelemetryDialog

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
Main780346297XXXmain1859653459 -> Config780346297XXXgetDimFile0[label=7];
Main780346297XXXmain1859653459 -> Config780346297XXXgetTmFile0[label=5];
Main780346297XXXmain1859653459 -> Config780346297XXXgetXmlFile0[label=6];
Main780346297XXXmain1859653459 -> Config780346297XXXload1808118735[label=3];
Main780346297XXXmain1859653459 -> TelemetryDialog780346297XXXTelemetryDialog0[label=1];
Main780346297XXXmain1859653459 -> TelemetryDialog780346297XXXsetDefaultFiles924985979[label=4];
    
}
@enduml